#!/bin/bash

set -euf -o pipefail

case "$1" in
    configure)
        mkdir -p /etc/ukefi
        if [ ! -f /etc/ukefi/directory ]; then
            echo "Ubuntu" > /etc/ukefi/directory
        fi
        if [ ! -f /etc/ukefi/cmdline ]; then
            cat /proc/cmdline > /etc/ukefi/cmdline
        fi
        ukefi-configure-boot install
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
