#!/bin/bash

set -euf -o pipefail

case "$1" in
    configure)
        ukefi-configure-boot install
        if [ ! -f /etc/ukefi/cmdline ]; then
            cat /proc/cmdline > /etc/ukefi/cmdline
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
