#!/bin/bash

set -euf -o pipefail

case "$1" in
    remove)
        echo "For safety, leaving boot entries and EFIs in place."
        echo "Use 'ukefi-configure-boot remove' to uninstall."
    ;;

    upgrade|deconfigure|failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
