#!/bin/bash

set -euf -o pipefail

case "$1" in
    remove)
        # TODO: prompt for confirmation (debconf?)
        ukefi-configure-boot remove
    ;;

    upgrade|deconfigure|failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
